-- Migration version recorded by Lovable Cloud when it applied the three
-- canonical migrations below as one operation:
--   20260710194500_agent_run_ownership.sql
--   20260710212000_atomic_campaign_quota.sql
--   20260710214500_internal_tick_jobs.sql
--
-- Intentionally a no-op in source. Keeping the version aligns local and
-- remote migration history without replaying duplicate CREATE FUNCTION calls
-- on a fresh database.
